rly_file = "Crewe.rly"
ttb_files = "Crewe May 2023.ttb"
ssn_files = "Crewe initial session.ssn"
country_code = "GB"
name = "Crewe"
description = ""
display_name = "Crewe"
author = "RailOS Dev Team"
release date = 